version: '3.3'
services:
  app:
    build: .
    image: ${DOCKER_IMAGE}
    restart: always
    networks:
      - servicenet
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - docker_jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7:ro
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1:/usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      resources:
        limits:
          cpus: '1.5'
          memory: 2000M
        reservations:
          cpus: '1.0'
          memory: 1500M
      restart_policy:
        condition: any
        delay: 5s
        window: 120s


networks:
  servicenet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}


volumes:
  docker_jenkins_home:
    external:
      name: docker-jenkins-home
