version: '3.3'
services:
  app:
    build: .
    image: ${DOCKER_IMAGE}
    restart: always
    networks:
      - servicenet
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - docker_jenkins_home:/var/jenkins_home


networks:
  servicenet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}


volumes:
  docker_jenkins_home:
    external:
      name: docker-jenkins-home
